name: Build
on: [push, pull_request]
  # release:
  #   types: [created]
  # push:
  #   tags:
  #   - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: mymindstorm/setup-emsdk@v10
      with:
        version: '2.0.24'
        actions-cache-folder: 'emsdk-cache'
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org/'
        scope: '@tybys'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm install
    # - name: Build WASM
    #   run: |
    #     echo $EMSDK
    #     emcc -v
    #     chmod +x ./build.sh
    #     ./build.sh Release
    - run: npm run build
    - name: Publish NPM
      if: ${{ startsWith(github.event.ref, 'refs/tags') }}
      run: npm publish --@tybys:registry=https://registry.npmjs.org/ --access public
