name: Build
on: [push, pull_request]
  # release:
  #   types: [created]
  # push:
  #   tags:
  #   - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: mymindstorm/setup-emsdk@v13
      with:
        version: '3.1.44'
        actions-cache-folder: 'emsdk-cache'
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org/'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm install
    # - name: Build WASM
    #   run: |
    #     echo $EMSDK
    #     emcc -v
    #     chmod +x ./build.sh
    #     ./build.sh Release
    - run: npm run build
    - name: Publish NPM
      if: ${{ startsWith(github.event.ref, 'refs/tags') }}
      run: npm publish
